
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        chain_provider:
            chain:
                providers: [ etudiant_provider, professeur_provider ]

        etudiant_provider:
            entity:
                class: App\Entity\Etudiant
                property: email

        professeur_provider:
            entity:
                class: App\Entity\Professeur
                property: email

    firewalls:
        etudiant:
            pattern: ^/Etudiant
            provider: etudiant_provider
            form_login:
                login_path: etudiant_login
                check_path: etudiant_login

        professeur:  # This should be at the same level as "etudiant"
            pattern: ^/Professeur
            provider: professeur_provider
            form_login:
                login_path: professeur_login
                check_path: professeur_login

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: chain_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
            access_denied_handler: App\Security\AccessDeniedHandler

    access_control:
        - { path: ^/etudiant, roles: ROLE_ETUDIANT }
        - { path: ^/professeur, roles: ROLE_PROFESSEUR }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
