security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        etudiant_provider:
            entity:
                class: App\Entity\Etudiant
                property: email

        professeur_provider:
            entity:
                class: App\Entity\Professeur
                property: email

    firewalls:
        etudiant:
            pattern: ^/Etudiant
            provider: etudiant_provider
            form_login:
                login_path: etudiant_login
                check_path: etudiant_login

        professeur:  # This should be at the same level as "etudiant"
            pattern: ^/Professeur
            provider: professeur_provider
            form_login:
                login_path: professeur_login
                check_path: professeur_login

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: etudiant_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout

    access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
